# Generated by Django 3.1.7 on 2021-04-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210402_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hit',
            options={'ordering': ('-status',)},
        ),
        migrations.AlterField(
            model_name='hit',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('failed', 'Failed'), ('completed', 'Completed')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('hitman', 'Hitman'), ('boss', 'Boss'), ('leader', 'Big Boss')], default='hitman', max_length=10),
        ),
    ]
