# Generated by Django 3.1.7 on 2021-04-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210404_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
