# Generated by Django 3.1.7 on 2021-04-04 03:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20210404_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='manager_of',
            field=models.ManyToManyField(related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
