# Generated by Django 3.1.7 on 2021-04-04 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_manager_of'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='manager_of',
            new_name='manages',
        ),
    ]
