# Generated by Django 3.1.7 on 2021-04-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210404_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('failed', 'Failed'), ('completed', 'Completed')], default='assigned', max_length=10),
        ),
    ]
