# Generated by Django 3.1.7 on 2021-04-06 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='manages',
            field=models.ManyToManyField(blank=True, related_name='manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
